[username]
format = " [â•­â”€user]($style)@"
style_user = "bold red"
style_root = "bold red"
show_always = true

[hostname]
format = "[$hostname]($style) in "
style = "bold dimmed red"
trim_at = "-"
ssh_only = false
disabled = false

[directory]
style = "purple"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "white"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
deleted = "x"



# Last param in the first line/row
[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = false

[time]
format = " ðŸ•™ $time($style)\n"
time_format = "%T"
style = "bright-white"
disabled = true

# Prompt: param 2 â””â”€
[character]
success_symbol = " [â•°â”€Î»](bold red)"
error_symbol = " [Ã—](bold red)"
